### ISSUE TITLE
Clipboard is not updated when executing cell

### ISSUE THREAD

**Issue by martinzh** [mroavi/vim-julia-cell#1] opened 2020-06-14 01:50 UTC
I'm trying to use the plugin with tmux in macOS Catalina 10.15.4 but somehow the clipboard is not updated when I execute a cell. `vim-slime` is working as running `:SlimeSendCurrentLine` works as expected. 

In the attached image you can see that `clipboard()` returns "last copy" which was the last thing I copied with `cmd+c` and it is send to Julia when I run `:JuliaCellExecuteCell`.

Is there something I'm doing wrong? I can provide more information if needed, thanks in advance.

<img width="1280" alt="Captura de Pantalla 2020-06-13 a la(s) 20 42 08" src="https://user-images.githubusercontent.com/3858887/84582805-7235c100-adb6-11ea-960e-ab921c2d7c9e.png">

**Comment by mroavi** [comment] 2020-06-14 09:30
Which clipboard program are you using? `xclip` or `xsel`?

Did you try this already (from the Q&A section in the docs)?:

Q: 'JuliaCellExecuteCell' and 'JuliaCellExecuteCellJump' do not execute ~
the correct code cell, or I get an error about 'can't open display', ~
'could not open display', 'could not connect to display', or something ~
similar, what do I do? ~
A: Make sure your DISPLAY environment variable is correct, especially after
re-attaching a screen or tmux session. In tmux you can update the DISPLAY
variable with the following command:

    eval $(tmux showenv -s DISPLAY)

**Comment by martinzh** [comment] 2020-06-14 18:34
I installed xquartz so I guess I'm using xclip. Running `tmux showenv -s DISPLAY` in tmux returns: `unset DISPLAY;` and running `xclip` in tmux returns: `Error: Can't open display: (null)` So I guess there's something missing in my tmux configration. Any help is appreciatted.

**Comment by mroavi** [comment] 2020-06-14 19:25
The problem is that your `DISPLAY` environment variable is not set. Try setting it inside your `.tmux.conf` adding this line:
```
set-option -g update-environment " DISPLAY"
```

**Comment by martinzh** [comment] 2020-06-15 14:43
I put that line in my `.tmux.conf` killed the `tmux` server and sourced without success (`clipboard()` in Julia shows the last `cmd+c` I did intead of the cell in the Julia script), I also tried using> [this](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard) which should allow `pbcopy` and `pbpaste` without success. I've tried using the iterm2 `tmux` integration and the terminal app with the same result...

**Comment by mroavi** [comment] 2020-08-02 11:30
I'm gonna close this since it seems a problem specific to your setup making it difficult for me to debug.

**Closed by mroavi** 2020-08-02 11:30 UTC
